name: "release"

on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "checkout"
        uses: actions/checkout@v3

      - name: "build"
        run: |
          chmod +x ./.github/workflows/scripts/tutorial_build_release.sh
          ./.github/workflows/scripts/tutorial_build_release.sh

          chmod +x ./.github/workflows/scripts/build_release.sh
          ./.github/workflows/scripts/build_release.sh
        env:
          ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}
          SUBGROW_DEMO_KEY_PASSWORD: ${{ secrets.SUBGROW_DEMO_KEY_PASSWORD }}
          SUBGROW_DEMO_STORE_PASSWORD: ${{ secrets.SUBGROW_DEMO_STORE_PASSWORD }}
          SUBGROW_DEMO_STORE_BASE64: ${{ secrets.SUBGROW_DEMO_STORE_BASE64 }}
          SUBGROW_DEMO_KEY_ALIAS: ${{ secrets.SUBGROW_DEMO_KEY_ALIAS }}

      - name: "github-releases"
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v0.0.${{github.run_id}}"
          prerelease: false
          files: |
            ./app/build/outputs/bundle/release/app-release.aab
            ./app/build/outputs/apk/release/app-release.apk
            ./app/build/outputs/apk/debug/app-debug.apk


      - name: "publish to PlayStore"
        run: |
          chmod +x ./.github/workflows/scripts/build_publish.sh
          ./.github/workflows/scripts/build_publish.sh
        env:
          ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}
          SUBGROW_DEMO_KEY_PASSWORD: ${{ secrets.SUBGROW_DEMO_KEY_PASSWORD }}
          SUBGROW_DEMO_STORE_PASSWORD: ${{ secrets.SUBGROW_DEMO_STORE_PASSWORD }}
          SUBGROW_DEMO_STORE_BASE64: ${{ secrets.SUBGROW_DEMO_STORE_BASE64 }}
          SUBGROW_DEMO_KEY_ALIAS: ${{ secrets.SUBGROW_DEMO_KEY_ALIAS }}
