#name: "run-tests-on-pr"
#
#on:
#  pull_request
#
#jobs:
#  pre-release:
#    name: "Pre Release"
#    runs-on: "ubuntu-latest"
#
#    steps:
#      - name: "checkout"
#        uses: actions/checkout@v3
